package com.example.weatherforecast

const val WEATHER_API_REFRESH_DELAY_SECONDS = 15 * 60 // 15 min

const val FORECAST_API_REFRESH_DELAY_SECONDS = 3 * 60 * 60 // 3h

const val FORECAST_FRAGMENT_WEATHER_ARG = "FORECAST_FRAGMENT_WEATHER_ARG"